### PR TITLE
Refactor neuroview out of settings panel, rename test snapshot images to have no ":" as part of title.

### PR DESCRIPTION
**Pull request by jrmartin**

### CODE REVIEW

**Comment by jrmartin** [comment]
@albatros13 Hi Natallia, I renamed the test/snapshots images as requested, without ":" as part of the title. 
I also moved out most of the Neuroview related code outside the Settings Panel, I'm still going to refactor more out of the Settings Panel in the upcoming sprint.

**Comment by albatros13** [comment]
Please make the Settings Panel visible by default or make sure the icons comply with the state (gear box when the panel is closed, little cross to close the open panel).

**Comment by jrmartin** [comment]
@albatros13 I made the settings panel fix

**Comment by jrmartin** [comment]
Handle now by PR https://github.com/open-physiology/open-physiology-viewer/pull/275

**Pull request closed without merging**
